spring.application.name=work.task
server.port=8082
springdoc.swagger-ui.path=/swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/work_task
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

external.user.service.baseurl=http://localhost:8081

logging.level.org.springframework.web=DEBUG